# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfba8073cbc21e7caa6e6a747e85feedc38897b7931d6aa02a0765c92189e9e24a96dc1789928899621e735cc056516bdabade360f1e437263a1881a79c2c2bd

test:
  secret_key_base: 7c9e24096399ce673764686a466964b523135358d67f041edc79b643cfa03c2ae572ff2c9289820a2a71bc0e485edfca7a294f185a07f4f7fc8aeafd534a91b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
